### ISSUE TITLE
Feature Wish: Named characters

### ISSUE THREAD

**Issue by fuzendesign** [AbeEstrada/atom-html-entities#3]
I'd love to see named character entities. This really is the way I see most characters being encoded by front-end people.

http://alumnus.caltech.edu/~leif/namedchar.html

**Comment by djmtype** [comment]
Sorry, to bring this up again… but, even declaring a utf-8 charset, then typing `©` is not as bulletproof or trustworthy as typing `&copy;`, correct? 

Since named entities are easier to remember than numeric, why not include it as an option?

**Comment by fuzendesign** [comment]
I believe Abe’s comment meant that there would be no need to encode any special characters as these would be translated just fine because of using utf-8 in the meta tag.

**Comment by Fridus** [comment]
+1
I want encode with the named entity. http://alumnus.caltech.edu/~leif/namedchar.html
`é` -> `&eacute;` and not `&#xE9;`.
You can maybe add a setting for that.
