### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by AgentME** [AbeEstrada/atom-html-entities#4]
(Atom's deprecation cop generated the following issue)

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/chris/.atom/packages/html-entities/lib/html-entities.coffee:5:9)
```

**Comment by AbeEstrada** [comment]
Fixed with https://github.com/AbeEstrada/atom-html-entities/commit/9db5a8ff30cb41e9df14cc788f4cb43a96547579

Thanks.
